
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Aug 02 13:09:14 MEST 2005
//----------------------------------------------------

package mwlParser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORK = 33;
  public static final int PERIOD = 12;
  public static final int NOT_EQUAL = 23;
  public static final int HIGH = 39;
  public static final int LPAREN = 2;
  public static final int GREATER = 20;
  public static final int SEMI = 8;
  public static final int INT = 37;
  public static final int LESS = 18;
  public static final int MINUS = 14;
  public static final int RPAREN = 3;
  public static final int AND = 24;
  public static final int OR = 25;
  public static final int BOOL = 38;
  public static final int COMMA = 9;
  public static final int LSQBRACK = 4;
  public static final int DIV = 17;
  public static final int LESS_EQUAL = 19;
  public static final int PLUS = 13;
  public static final int ASSIGN = 10;
  public static final int IF = 27;
  public static final int EOF = 0;
  public static final int LOW = 40;
  public static final int TRUE = 35;
  public static final int GREATER_EQUAL = 21;
  public static final int error = 1;
  public static final int NUMBER = 43;
  public static final int MOD = 16;
  public static final int TIMES = 15;
  public static final int COLON = 11;
  public static final int LBRACE = 6;
  public static final int ELSE = 29;
  public static final int SKIP = 26;
  public static final int WHILE = 31;
  public static final int THEN = 28;
  public static final int RBRACE = 7;
  public static final int RSQBRACK = 5;
  public static final int END = 30;
  public static final int USER = 41;
  public static final int FALSE = 36;
  public static final int EQUAL_EQUAL = 22;
  public static final int LENGTH = 34;
  public static final int DO = 32;
  public static final int IDENTIFIER = 42;
}

